# .circleci/config.yml

version: 2.1
jobs:
  build_test:
    macos:
      xcode: "13.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          command: xcodebuild -project demo-circle-ci.xcodeproj -scheme "demo-circle-ci" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8 Plus,OS=15.0" -enableCodeCoverage YES test
      - store_test_results:
          path: test-results

workflows:
  version: 2.1
  primary:
    jobs:
      - build_test
